services:
  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=1000
      - GID=1000
    volumes:
      - ./synapse:/data
    depends_on:
      - synapse_db
    networks:
      m_network:
        ipv4_address: 10.10.10.2

  synapse_db:
    image: docker.io/postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding='UTF8' --lc-collate='C' --lc-ctype='C'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      m_network:
        ipv4_address: 10.10.10.5

  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes:
      - ./element-config.json:/app/config.json
    networks:
      m_network:
        ipv4_address: 10.10.10.3

  reverse-proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wellknown:/usr/share/nginx/html/.well-known:ro
    ports:
      - "4100:80"
    networks:
      m_network:
        ipv4_address: 10.10.10.4

networks:
  m_network:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
